#ddev-generated
version: '3.6'
services:
  opensearch:
    container_name: ddev-${DDEV_SITENAME}-opensearch
    hostname: ${DDEV_SITENAME}-opensearch
    image: opensearchproject/opensearch:1.2.4
    expose:
      - "9200"
      - "9201"
      - "9300"
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - opensearch:/usr/share/opensearch/data
      - ".:/mnt/ddev_config"
  web:
    links:
      - opensearch:opensearch

volumes:
  opensearch:
